version: '3'

services:
  deno:
    image: hayd/deno:latest
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    working_dir: /app
    command: ["run", "--allow-net", "--allow-read", "main.ts"]
