version: '3'

services:
  backend:
    container_name: backend
    image: hayd/deno:latest
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: ["run", "--allow-net", "--allow-read", "main.ts"]
  frontend:
    container_name: frontend
    image: node:alpine
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["npm", "run", "serve"]
